### ISSUE TITLE
Failed to start app

### ISSUE THREAD

**Issue by billbarni** [tilersmyth/newstand#1] opened 2017-10-25 19:43 UTC
Sorry if this is a noobish question. When I try to start app I get the following error:

```
C:\Users\William\Desktop\newstand\node_modules\express-jwt\lib\index.js:20
  if (!options || !options.secret) throw new Error('secret should be set');
                                   ^
Error: secret should be set
    at module.exports (C:\Users\William\Desktop\newstand\node_modules\express-jwt\lib\index.js:20:42)
    at Object.<anonymous> (C:\Users\William\Desktop\newstand\dist\server\auth\auth.service.js:9:19)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\William\Desktop\newstand\dist\server\api\user\user.router.js:14:12)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
[nodemon] app crashed - waiting for file changes before starting...
```

Where do I need to set the secret to make it work? Thanks for sharing your code with the community.

**Comment by tilersmyth** [comment] 2017-10-25 20:10
Hey @billbarni - certainly understandable why you came across this error. I just committed some changes that include a '.env-sample' file, which contains environment sensitive variables you will need (including the secret).. To ensure a working app on your end - pull the latest code, rename '.env-sample' to '.env' and enter the necessary API variables in the .env file. 

Note: While Google and FB oAuth credentials aren't required (you can use local authentication), you will need API credentials from getstream.io.

thanks for checking this project out! I will close this issue, but feel free reach out with anything else.

**Closed by tilersmyth** 2017-10-25 20:10 UTC

**Comment by billbarni** [comment] 2017-10-26 18:38
Now Im getting this error when trying to create a new local account:

```
[0] 2017-10-26T16:30:25.364-0200 I COMMAND  [ftdc] serverStatus was very slow: { after basic: 0, after asserts: 433, aft
er backgroundFlushing: 433, after connections: 433, after dur: 433, after extra_info: 433, after globalLock: 433, after
locks: 433, after network: 433, after opLatencies: 433, after opcounters: 433, after opcountersRepl: 433, after repl: 55
3, after security: 553, after storageEngine: 553, after tcmalloc: 553, after wiredTiger: 1073, at end: 1683 }
[1] [HPM] Error occurred while trying to proxy request /api/users/create from localhost:4200 to http://localhost:3000 (E
CONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)
[1] [HPM] Error occurred while trying to proxy request /api/users/create from localhost:4200 to http://localhost:3000 (E
CONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)
```

**Comment by tilersmyth** [comment] 2017-10-30 14:10
Ok great. I was just about to respond to say that I'm unable to reproduce the error on a fresh install. Also, this project is obviously in its infancy with plenty to do so feel free to create a PR if you want to contribute.
